### ISSUE TITLE
Proper Treasure Format, faulty connection?

### ISSUE THREAD

**Issue by GhostXavier** [ArchmageInc/RandomEncounters#13]
http://pastebin.com/aY0BeayJ

The above is the full list of the treasures.json. The server fails to load these properly into the encounters.

An example of the Encounters code in case the treasures group are mislabeled.
http://pastebin.com/WSLmhXgQ

I can't seem to find anything wrong with the code but the server still fails to detect the specific categories. Ex, it would state "MainLoot" would be invalid for castle4.

**Comment by ArchmageInc** [comment]
The treasures.json in the paste is not valid JSON. Starting at line 54, there are invalid object literals enclosing each treasure option.

**Comment by GhostXavier** [comment]
Just noticed the added brackets for no reason. Thanks for pointing out the flaw (horribly new to script writing/editing/reading haha)
