### ISSUE TITLE
Suggestion / worldedit

### ISSUE THREAD

**Issue by cataclisto** [ArchmageInc/RandomEncounters#17]
Worldedit has a feature that allows builds to be pasted without air, (//paste -a) Could you add a line within your json files for the builds to utilize this feature? this way i can have larger sky type builds randomly spawn without crashing the server or small trees spawn in without making a obvious worldedit square box on the ground below it

**Comment by ArchmageInc** [comment]
Yeah, I have been tossing around ideas on how to best implement this. It would be simple enough just to have a flag to not paste air. There is a lot more to what I really hope to accomplish, but I will try to squeeze that into the 0.4.x release.
